name: Trigger auto deployment for containertestwic

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containertestwic-AutoDeployTrigger-6da41e44-6814-4c03-bfd1-93f3d7905e61.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: testcontainerregistryojy.azurecr.io
          username: ${{ secrets.CONTAINERTESTWIC_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERTESTWIC_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testcontainerregistryojy.azurecr.io/containertestwic:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERTESTWIC_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containertestwic -g TEST_WIC --server testcontainerregistryojy.azurecr.io --username  ${{ secrets.CONTAINERTESTWIC_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERTESTWIC_REGISTRY_PASSWORD }}
            az containerapp update -n containertestwic -g TEST_WIC --image testcontainerregistryojy.azurecr.io/containertestwic:${{ github.sha }}
